---
roles:
  - name: geerlingguy.nginx
    version: "3.3.0"
  - name: geerlingguy.docker
    version: "8.0.1"
  - name: geerlingguy.certbot
    version: "5.4.1"
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.crypto
