---
roles:
  - name: geerlingguy.apache
    version: "3.3.0"
  - name: geerlingguy.docker
    version: "7.0.1"
  - name: geerlingguy.certbot
    version: "5.1.0"
collections:
  - name: ansible.posix
  - name: community.general
