---

- name: "Set host address for {{site.id}}"
  ansible.builtin.set_fact:
    host_address: >-
      {{ hostvars[host]['ansible_host'] if inventory_hostname!=host else 'localhost' }}

- name: "Site {{site.id}} is Omeka-S site?"
  ansible.builtin.set_fact:
    site_is_om: "{{site.om_settings is defined |default(false)}}"
  
- name: "Site {{site.id}} is WordPress site?"
  ansible.builtin.set_fact:
    site_is_wp: "{{site.wp_settings is defined |default(false)}}"

- name: "Getting IP restrictions for {{site.id}}"
  ansible.builtin.include_tasks:
    file: get_ip_restrictions.yml

- name: "Initialize login_locations to empty list"
  ansible.builtin.set_fact:
    login_locations: []

- name: "Set login page location for Wordpress site"
  ansible.builtin.set_fact:
    login_locations: ["wp-admin"]
  when: site_is_wp and site.login_locations is not defined

- name: "Set login page location for Omeka-S site"
  ansible.builtin.set_fact:
    login_locations: ["login"]
  when: site_is_om and site.login_locations is not defined

- name: "Set login_locations to explicitly set login_locations for site {{site.id}}"
  ansible.builtin.set_fact:
    login_locations: "{{site.login_locations}}"
  when: site.login_locations is defined

- name: "Set http_proto to default 'https'"
  ansible.builtin.set_fact:
    http_proto: "https"
  
- name: "Set http_proto to default site.http_container_proto"
  ansible.builtin.set_fact:
    http_proto: "{{site.http_container_proto}}"
  when: site.http_container_proto is defined

- name: "Set '/' when not in login_locations"
  ansible.builtin.set_fact:
    locations: "{{ {
        'slash':'proxy_pass '+http_proto+'://'+host_address+':'+site.port|string+';'
      } }}"
  when: '"/" not in login_locations and "slash" not in login_locations'
  
- name: "Set '/' when in login_locations"
  ansible.builtin.set_fact:
    locations: "{{ {
        'slash':'proxy_pass '+http_proto+'://'+host_address+':'+site.port|string+';'+ip_restrictions
      } }}"
  when: '"/" in login_locations or "slash" in login_locations'

- ansible.builtin.debug:
    msg: "login_locations={{login_locations}}"
  
- name: "Adding additional login locations"
  ansible.builtin.set_fact:
    locations: "{{ locations| combine({location:'proxy_pass '+http_proto+'://'+host_address+':'+site.port|string+'/'+location+';'+ip_restrictions}) }}"
  loop: "{{login_locations}}"
  when: 'location!="/" and location!="slash"'
  loop_control:
    loop_var: location
  #login_location:'proxy_pass '+http_proto+'://'+host_address+':'+site.port|string+'/'+login_location+';'+ip_restrictions
  
- ansible.builtin.debug:
    msg: "locations={{locations}}"
  
- name: "Create domains as empty string"
  ansible.builtin.set_fact:
    domains: ""
  
- name: "Create domains string"
  ansible.builtin.set_fact:
    domains: '{{domains+" "+domain}}'
  loop: "{{ site.domains }}"
  loop_control:
    loop_var: domain
    label: "{{domain}}"

- name: "Trim domains string"
  ansible.builtin.set_fact:
    domains: "{{domains|trim}}"
  
- name: "Add to nginx_vhosts for site {{site.id}}"
  ansible.builtin.set_fact:
    nginx_vhosts: "{{nginx_vhosts|default([]) + [{
      'listen': '443 ssl',
      'server_name': domains,
      'state':'present','template':'proxy_vhost.j2',
      'filename': site.domains[0],
      'locations': locations},
      {'listen': '80',
      'server_name': domains,
      'filename': site.domains[0]+'.80',
      'state': 'present',
      'template': 'proxy_vhost_redirect.j2'
      }]}}"
  when: site.domains is defined and site.domains|length>0

- name: "Set no default domain"
  ansible.builtin.set_fact:
    default_domain: []

- name: "Set default domain to IP.cloud.computecanada.ca"
  ansible.builtin.set_fact:
    default_domain: "{{[ansible_host|replace('.','-')+'.cloud.computecanada.ca']}}"
  when: include_cc_domain is not defined or include_cc_domain==true

- name: "Add to site_domains list for site {{site.id}}"
  ansible.builtin.set_fact:
    site_domains: "{{site_domains|default(default_domain) + [domain]}}"
  loop: "{{ site.domains }}"
  loop_control:
    loop_var: domain
    label: "{{domain}}"
