---

- name: "Getting IP restrictions for {{site.id}}"
  ansible.builtin.include_tasks:
    file: get_ip_restrictions.yml

- name: "Initialize autoindex"
  ansible.builtin.set_fact:
    auto_index_config: "autoindex off;\n"

- name: "Set autoindex"
  ansible.builtin.set_fact:
    auto_index_config: "autoindex on;\n"
  when: site.autoindex is defined and site.autoindex==true

- name: "Set login_locations to empty list if not yet defined"
  ansible.builtin.set_fact:
    login_locations: []

- name: "Set login_locations to explicitly set login_locations for site {{site.id}}"
  ansible.builtin.set_fact:
    login_locations: "{{site.login_locations}}"
  when: site.login_locations is defined

- name: "Set '/' location for site {{site.id}} at {{site.root}} when not in login_locations"
  ansible.builtin.set_fact:
    locations: "{{ {'slash':'try_files $uri $uri/ =404;\n'+auto_index_config} }}"
  when: '"/" not in login_locations and "slash" not in login_locations'

- name: "Set '/' location for site {{site.id}} at {{site.root}} when in login_locations"
  ansible.builtin.set_fact:
    locations: "{{ {'slash':'try_files $uri $uri/ =404;\n'+auto_index_config+ip_restrictions} }}"
  when: '"/" in login_locations or "slash" in login_locations'

- name: "Adding additional login locations"
  ansible.builtin.set_fact:
    locations: "{{ locations| combine({location:'try_files $uri $uri/ =404;\n'+ip_restrictions}) }}"
  loop: "{{login_locations}}"
  when: 'location!="/" and location!="slash"'
  loop_control:
    loop_var: location

- name: "Create domains as empty string"
  ansible.builtin.set_fact:
    domains: ""

- name: "Create domains string"
  ansible.builtin.set_fact:
    domains: '{{domains+" "+domain}}'
  loop: "{{ site.domains }}"
  loop_control:
    loop_var: domain
    label: "{{domain}}"

- name: "Trim domains string"
  ansible.builtin.set_fact:
    domains: "{{domains|trim}}"

- name: "Add to nginx_vhosts for site {{site.id}}"
  ansible.builtin.set_fact:
    nginx_vhosts: "{{nginx_vhosts|default([]) + [{
      'listen': '443 ssl',
      'server_name': domains,
      'state':'present','template':'proxy_vhost.j2',
      'filename': site.domains[0],
      'root': site.root,
      'locations': locations},
      {'listen': '80',
      'server_name': domains,
      'filename': site.domains[0]+'.80',
      'state': 'present',
      'template': 'proxy_vhost_redirect.j2'
      }]}}"
  when: site.domains is defined and site.domains|length>0

- name: "Set no default domain"
  ansible.builtin.set_fact:
    default_domain: []

- name: "Add to site_domains list for site {{site.id}}"
  ansible.builtin.set_fact:
    site_domains: "{{site_domains|default(default_domain) + [domain]}}"
  loop: "{{ site.domains }}"
  loop_control:
    loop_var: domain
    label: "{{domain}}"
