---

- name: "Get site {{site.id}} settings for {{host}}"
  ansible.builtin.include_tasks:
    file: generate_site_settings.yml
  when: hostvars[host] is defined and hostvars[host].sites is defined
  loop: "{{hostvars[host].sites}}"
  loop_control:
    loop_var: site
    label: "{{site.id}}"

#- name: "Stop for debugging"
#  ansible.builtin.fail:
#    msg: "Stopping for debugging"
