---

- name: "Set host address"
  ansible.builtin.set_fact:
    host_address: >-
      {{ hostvars[host]['ansible_host'] if inventory_hostname!=host else 'localhost' }}

- name: "Site {{site.id}} is Omeka-S site?"
  ansible.builtin.set_fact:
    site_is_om: "{{site.om_settings is defined |default(false)}}"
  
- name: "Site {{site.id}} is WordPress site?"
  ansible.builtin.set_fact:
    site_is_wp: "{{site.wp_settings is defined |default(false)}}"
    
- name: "Site {{site.id}} login has IP restrictions?"
  ansible.builtin.set_fact:
    has_ip_restrictions: "{{site.login_ips is defined and site.login_ips|length|int>0}}"

- ansible.builtin.debug:
    msg: "has_ip_restrictions={{has_ip_restrictions}}"
    
- name: "Initialize ip_restrictions to empty string"
  ansible.builtin.set_fact:
    ip_restrictions: ""

- name: "Set ip_restrictions to deny all"
  ansible.builtin.set_fact:
    ip_restrictions: "denay all;\n"
  when: has_ip_restrictions
  
- name: "Add allowed login IPs for site {{site.id}}"
  ansible.builtin.set_fact:
    ip_restrictions: "allow {{ip}};\n{{ip_restrictions}}"
  loop: "{{site.login_ips}}"
  loop_control:
    loop_var: ip
    label: "{{ip}}"
  when: has_ip_restrictions
  
- name: "Set login page location for Wordpress site"
  ansible.builtin.set_fact:
    login_location: "wp-admin"
  when: site_is_wp
  
- name: "Set login page location for Omeka-S site"
  ansible.builtin.set_fact:
    login_location: "login"
  when: site_is_om
  
- name: "Add to nginx_vhosts for site {{site.id}}"
  ansible.builtin.set_fact:
    nginx_vhosts: "{{nginx_vhosts|default([]) + [{
      'listen': '443 ssl',
      'server_name': domain,
      'state':'present','template':'proxy_vhost.j2',
      'filename': domain,
      'locations':{
        'slash':'proxy_pass https://'+host_address+':'+site.port|string+';',
        login_location:'proxy_pass https://'+host_address+':'+site.port|string+'/'+login_location+'/;'+ip_restrictions
      }
      },{
      'listen': '80',
      'server_name': domain,
      'filename': domain+'.80',
      'state': 'present',
      'template': 'proxy_vhost_redirect.j2'
      }]}}"
  loop: "{{ site.domains }}"
  loop_control:
    loop_var: domain
    label: "{{domain}}"

- name: "Add to proxy_domains list for site {{site.id}}"
  ansible.builtin.set_fact:
    proxy_domains: "{{proxy_domains|default([ansible_host|replace('.','-')+'.cloud.computecanada.ca']) + [domain]}}"
  loop: "{{ site.domains }}"
  loop_control:
    loop_var: domain
    label: "{{domain}}"
