services:
  
  web:
    image: omeka-s:latest
    build: ./
    restart: always
    ports:
      - ${LOCAL_PORT}:80
    environment:
      OMEKAS_DB_HOST: db
      OMEKAS_DB_USER: ${DB_USER}
      OMEKAS_DB_PASSWORD: ${DB_PASSWORD}
      OMEKAS_DB_NAME: ${DB_NAME}
    volumes:
      - webv:/var/www/html
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD:  ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - dbv:/var/lib/mysql
    healthcheck:
      test:  "mysql -u$DB_USER -p$DB_PASSWORD $DB_NAME -e\"show tables;\""
      timeout: 30s
      retries: 100

volumes:
  webv:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./${SITE_NAME}/volumes/web
  dbv:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ./${SITE_NAME}/volumes/db
      
