---

- name: "Set extra vhosts params"
  ansible.builtin.set_fact:
    extra_vhost_parameters: |
      RewriteEngine On
      RewriteCond %{HTTPS} off
      RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI}

- name: "Create site vhosts, vhosts_ssl, and certbot per site"
  ansible.builtin.include_tasks:
    file: vhosts_vars.yml
  loop: "{{ sites }}"
  loop_control:
    loop_var: site
    label: "{{ site.id }}"

#- name: "Print created vhosts settings"
#  ansible.builtin.debug:
#    msg: "{{ vhosts_mine }}"
#- name: "Print created vhosts_ssl settings"
#  ansible.builtin.debug:
#    msg: "{{ vhosts_ssl_mine }}"
#- name: "Print certbot_certs_mine"
#  ansible.builtin.debug:
#    msg: "{{ certbot_certs_mine }}"

- ansible.builtin.include_role:
    name: geerlingguy.apache
  vars:
    apache_mods_enabled:
      - rewrite
      - ssl
      - proxy
      - proxy_http
      - headers
    apache_ignore_missing_ssl_certificate: false
    apache_remove_default_vhost: true
    apache_vhosts: "{{ vhosts_mine }}"
    apache_vhosts_ssl: "{{ vhosts_ssl_mine }}"

- ansible.builtin.include_role:
    name: geerlingguy.certbot
  vars:
    certbot_install_method: package
    certbot_create_if_missing: true
    certbot_create_standalone_stop_services:
      - apache2
    certbot_hsts: true
    certbot_admin_email: "{{ cert_bot_email }}"
    certbot_certs: "{{ certbot_certs_mine }}"
    
- ansible.builtin.include_role:
    name: geerlingguy.docker
  vars:
    docker_install_compose_plugin: true
    docker_install_compose: false

- name: Disable Apache2 proxy requests
  ansible.builtin.lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^ProxyRequests'
    line: "ProxyRequests Off"
  register: proxy_request_off

# TODO: do I need to set headers? I did this on the r-shiny server for some
# reason, but maybe that is specific to rshiny apps
- name: Ensure header X-Forwarded-Proto gets set
  ansible.builtin.lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^RequestHeader set "X-Forwarded-Proto"'
    line: 'RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}'
  register: request_header_proto

- name: Adjust headers
  ansible.builtin.lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^RequestHeader set "X-Forwarded-SSL"'
    line: 'RequestHeader set "X-Forwarded-SSL" expr=%{HTTPS}'
  register: request_header_ssl

- name: Restart apache
  ansible.builtin.service:
    name: apache2
    state: restarted
  when: proxy_request_off.changed or request_header_proto.changed or request_header_ssl.changed
