FROM {{ om_defaults.base_docker_image }}

RUN apt-get update && apt-get install -y imagemagick unzip libzip-dev

RUN set -ex; \
  docker-php-ext-install -j "$(nproc)" \
    pdo_mysql \
    zip \
  ;

VOLUME /var/www/html

#Install Omeka CLI
RUN curl -fL -o /usr/bin/omeka-s-cli {{ om_defaults.cli_url }};chmod +x /usr/bin/omeka-s-cli

CMD ["/bin/bash"]

