FROM {{ om_defaults.base_docker_image }}

RUN apt-get update && apt-get install -y imagemagick unzip libzip-dev
RUN curl -fL -o /usr/src/omeka-s.zip https://github.com/omeka/omeka-s/releases/download/v{{ om_defaults.omeka_s_version }}/omeka-s-{{ om_defaults.omeka_s_version }}.zip
RUN sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride all/' /etc/apache2/apache2.conf

RUN set -ex; \
  docker-php-ext-install -j "$(nproc)" \
    pdo_mysql \
    zip \
  ;

#Use production php configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN a2enmod rewrite

VOLUME /var/www/html

COPY --chmod=755 docker-entrypoint.sh /usr/local/bin/

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["apache2-foreground"]
