- name: "Create {{ site.id }} site directory as needed"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0770'

- name: "Create volumes directory for {{ site.id }} as needed"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0770'

- name: "Create web root volume for {{ site.id }} as needed"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/web"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: '0770'

- name: "Create apache config volume for {{ site.id }} as needed"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/ap_conf"
    state: directory
    owner: "root"
    group: "root"
    mode: '0770'

- name: "Create database volume directories for {{ site.id }} as needed"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/db"
    state: directory
    owner: "mysql"
    group: "mysql"
    mode: '0770'
