- name: "Check if Omeka S site {{ site.id }} already initialized"
  ansible.builtin.command: >
    docker run --rm --volumes-from "{{ site.id }}"-web-1 
    --network container:"{{ site.id }}"-web-1 "{{ om_defaults.cli_image }}"
    omeka-s-cli core:status
  register: omeka_site_initialized_result
  failed_when: omeka_site_initialized_result.rc != 0
  changed_when: false
  
- name: "Initlize Omeka-S site {{ site.id }}"
  ansible.builtin.command: >
    docker run --rm --volumes-from "{{ site.id }}"-web-1 
    --network container:"{{ site.id }}"-web-1 "{{ om_defaults.cli_image }}"
    omeka-s-cli core:install 
    --admin-name "{{ site.om_settings.initial.admin_display_name }}"
    --admin-email "{{ site.om_settings.initial.admin_email }}"
    --admin-password "{{ site.om_settings.initial.admin_password }}"
    --title "{{ site.om_settings.initial.title }}"
  when: "'not_installed' in omeka_site_initialized_result.stdout"
