- name: "Ensure modules directory writable by webserver"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/web/modules"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0770

- name: "Ensure themes directory writable by webserver"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/web/themes"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0770

- name: "Ensure database.ini only readable by www-data"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/web/config/database.ini"
    state: file
    owner: "www-data"
    group: "www-data"
    mode: 0400

- name: "Set permissions on web/files"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/web/files"
    state: directory
    owner: "www-data"
    group: "{{ ansible_user }}"
    mode: 0775
