- name: "Modules directory should be writable?"
  ansible.builtin.set_fact:
    modules_dir_writeable: "{{ site.om_settings.config.modules_dir_writeable_by_webserver | default(om_default_modules_dir_writeable) }} | bool"
    
- name: "Themes directory should be writable?"
  ansible.builtin.set_fact:
    themes_dir_writeable: "{{ site.om_settings.config.themes_dir_writeable_by_webserver | default(om_default_themes_dir_writeable) }} | bool"

- name: "Ensure modules directory writable by webserver"
  ansible.builtin.file:
    path: "/home/{{ default_ansible_user }}/{{ site.id }}/volumes/web/modules"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0770
  when: modules_dir_writeable
  
- name: "Ensure modules directory not writable by webserver"
  ansible.builtin.file:
    path: "/home/{{ default_ansible_user }}/{{ site.id }}/volumes/web/modules"
    state: directory
    owner: "root"
    group: "root"
    mode: 0750
  when: not modules_dir_writeable
  
- name: "Ensure themes directory writable by webserver"
  ansible.builtin.file:
    path: "/home/{{ default_ansible_user }}/{{ site.id }}/volumes/web/themes"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0770
  when: themes_dir_writeable
  
- name: "Ensure themes directory not writable by webserver"
  ansible.builtin.file:
    path: "/home/{{ default_ansible_user }}/{{ site.id }}/volumes/web/themes"
    state: directory
    owner: "root"
    group: "root"
    mode: 0750
  when: not themes_dir_writeable
  
- name: "Ensure database.ini only readable by www-data"
  ansible.builtin.file:
    path: "/home/{{ default_ansible_user }}/{{ site.id }}/volumes/web/config/database.ini"
    state: file
    owner: "www-data"
    group: "www-data"
    mode: 0400
