---

- name: "Set root path when no slash on end"
  ansible.builtin.set_fact:
    root_path: "{{site.root}}"

- name: "Set root path when slash on end"
  ansible.builtin.set_fact:
    root_path: "{{site.root[:-1]}}"
  when: site.root[-1]=="/"

- name: "Set dir_name from site.root"
  ansible.builtin.set_fact:
    dir_name: "{{root_path|basename}}"

- name: "Set dir_name from site.root"
  ansible.builtin.set_fact:
    base_path: "{{root_path|dirname}}"
