---

- hosts: wp_hosts
  become: true
  become_method: sudo
  gather_facts: false

  tasks:

    - name: "Install restic"
      ansible.builtin.apt:
        name: restic
        state: present

    # TODO: Do I want to update restic every time I run this?
    # How often do I run this?
    #- name: "Update restic"
    #  ansible.builtin.command: restic self-update

    - name: "Backup Wordpress sites"
      ansible.builtin.include_tasks:
        file: wp_backup_site.yml
      loop: "{{ sites }}"
      loop_control:
        label: "{{ item.id }}"
      vars:
        site: "{{ item }}"
