- name: "Set file permissions for .htaccess"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/web/.htaccess"
    owner: "www-data"
    group: "www-data"
    mode: u=rw,g=r,o=r

- name: "Set file permissions for index.php"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/web/index.php"
    owner: "www-data"
    group: "www-data"
    mode: u=rw,g=,o=

- name: "Set file permissions for wp-config.php"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/web/wp-config.php"
    owner: "www-data"
    group: "www-data"
    mode: u=rw,g=,o=

- name: "Set file permissions for wp-admin/ directory"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/web/wp-admin/"
    owner: "www-data"
    group: "www-data"
    mode: u=wrx,g=,o=
    
- name: "Set file permissions for wp-includes/ directory"
  ansible.builtin.file:
    path: "{{ container_base }}/{{ site.id }}/volumes/web/wp-includes/"
    owner: "www-data"
    group: "www-data"
    mode: u=wrx,g=,o=
